services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ./ticketmonster

volumes:
  db_data:
    name: ticketmonster_data
